// Code generated by ent, DO NOT EDIT.

//go:build tools
// +build tools

// Package internal holds a loadable version of the latest schema.
package internal

const Schema = `{"Schema":"github.com/woocoos/entco/integration/helloapp/ent/schema","Package":"github.com/woocoos/entco/integration/helloapp/ent","Schemas":[{"name":"World","config":{"Table":""},"fields":[{"name":"id","type":{"Type":12,"Ident":"","PkgPath":"","PkgName":"","Nillable":false,"RType":null},"position":{"Index":0,"MixedIn":true,"MixinIndex":0},"schema_type":{"mysql":"int"},"annotations":{"ProtoField":{"Number":1,"Type":0,"TypeName":""}}},{"name":"tenant_id","type":{"Type":12,"Ident":"","PkgPath":"","PkgName":"","Nillable":false,"RType":null},"immutable":true,"position":{"Index":0,"MixedIn":true,"MixinIndex":1},"schema_type":{"mysql":"int"}},{"name":"name","type":{"Type":7,"Ident":"","PkgPath":"","PkgName":"","Nillable":false,"RType":null},"position":{"Index":0,"MixedIn":false,"MixinIndex":0}}],"policy":[{"Index":0,"MixedIn":false,"MixinIndex":0}]}],"Features":["privacy","entql","schema/snapshot"]}`
