// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/woocoos/entco/integration/gentest/ent/runtime.go

const (
	Version = "v0.12.4-0.20230702151415-1ec75238037c" // Version of ent codegen.
)
