// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"context"

	"github.com/woocoos/entco/integration/helloapp/ent/schema"
	"github.com/woocoos/entco/integration/helloapp/ent/world"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	world.Policy = privacy.NewPolicies(schema.World{})
	world.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := world.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
}

const (
	Version = "v0.12.1"                                         // Version of ent codegen.
	Sum     = "h1:bqK+WMwfjpTsFiXx9tQSEZMNLyAADSx5Y1xySjT4Tm8=" // Sum of ent codegen.
)
